# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "test-unit", "~> 3.3"

gem "colorize", "~> 0.8.1"

gem "tty-cursor", "~> 0.7.0"

gem "tty-progressbar", "~> 0.17.0"
